# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 737)
        self.setWindowIcon(QIcon('./icons/Title.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 941, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DateLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.DateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DateLabel.setObjectName("DateLabel")
        self.horizontalLayout.addWidget(self.DateLabel)
        self.DateShow = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.DateShow.setText("")
        self.DateShow.setObjectName("DateShow")
        self.horizontalLayout.addWidget(self.DateShow)
        self.TimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLabel.setObjectName("TimeLabel")
        self.horizontalLayout.addWidget(self.TimeLabel)
        self.TimeShow = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TimeShow.setText("")
        self.TimeShow.setObjectName("TimeShow")
        self.horizontalLayout.addWidget(self.TimeShow)
        self.SumLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SumLabel.setObjectName("SumLabel")
        self.horizontalLayout.addWidget(self.SumLabel)
        self.SumShow = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.SumShow.setText("")
        self.SumShow.setObjectName("SumShow")
        self.horizontalLayout.addWidget(self.SumShow)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(260, 9, 481, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 100, 671, 571))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Sub_Rank = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Sub_Rank.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Sub_Rank.setAlignment(QtCore.Qt.AlignCenter)
        self.Sub_Rank.setObjectName("Sub_Rank")
        self.verticalLayout_2.addWidget(self.Sub_Rank)
        self.RankList = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.RankList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.RankList.setUndoRedoEnabled(True)
        self.RankList.setObjectName("RankList")
        self.verticalLayout_2.addWidget(self.RankList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Sub_Name = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Sub_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Sub_Name.setObjectName("Sub_Name")
        self.verticalLayout_3.addWidget(self.Sub_Name)
        self.NameList = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.NameList.setObjectName("NameList")
        self.verticalLayout_3.addWidget(self.NameList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Sub_ShowDays = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Sub_ShowDays.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Sub_ShowDays.setAlignment(QtCore.Qt.AlignCenter)
        self.Sub_ShowDays.setObjectName("Sub_ShowDays")
        self.verticalLayout_6.addWidget(self.Sub_ShowDays)
        self.ShowDaysList = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.ShowDaysList.setMaximumSize(QtCore.QSize(80, 16777215))
        self.ShowDaysList.setObjectName("ShowDaysList")
        self.verticalLayout_6.addWidget(self.ShowDaysList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Sub_CurSum = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Sub_CurSum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Sub_CurSum.setAlignment(QtCore.Qt.AlignCenter)
        self.Sub_CurSum.setObjectName("Sub_CurSum")
        self.verticalLayout_4.addWidget(self.Sub_CurSum)
        self.CurSumList = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.CurSumList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CurSumList.setObjectName("CurSumList")
        self.verticalLayout_4.addWidget(self.CurSumList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Sub_TotalBox = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.Sub_TotalBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Sub_TotalBox.setAlignment(QtCore.Qt.AlignCenter)
        self.Sub_TotalBox.setObjectName("Sub_TotalBox")
        self.verticalLayout_5.addWidget(self.Sub_TotalBox)
        self.TotalBoxList = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.TotalBoxList.setMaximumSize(QtCore.QSize(100, 16777215))
        self.TotalBoxList.setObjectName("TotalBoxList")
        self.verticalLayout_5.addWidget(self.TotalBoxList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(730, 100, 167, 80))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.combobox_Name = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.combobox_Name.setMaximumSize(QtCore.QSize(16777215, 50))
        self.combobox_Name.setObjectName("combobox_Name")
        self.verticalLayout_7.addWidget(self.combobox_Name)
        self.comboBox_ChooseName = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        self.comboBox_ChooseName.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBox_ChooseName.setObjectName("comboBox_ChooseName")
        self.verticalLayout_7.addWidget(self.comboBox_ChooseName)
        self.ChooseConfirmed = QtWidgets.QPushButton(self.centralwidget)
        self.ChooseConfirmed.setGeometry(QtCore.QRect(900, 150, 71, 28))
        self.ChooseConfirmed.setObjectName("ChooseConfirmed")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(720, 270, 271, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.BoxRate = QtWidgets.QLabel(self.formLayoutWidget)
        self.BoxRate.setText("")
        self.BoxRate.setObjectName("BoxRate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.BoxRate)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ShowNumber = QtWidgets.QLabel(self.formLayoutWidget)
        self.ShowNumber.setText("")
        self.ShowNumber.setObjectName("ShowNumber")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ShowNumber)
        self.avgPeople = QtWidgets.QLabel(self.formLayoutWidget)
        self.avgPeople.setText("")
        self.avgPeople.setObjectName("avgPeople")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.avgPeople)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.MovieName = QtWidgets.QLabel(self.formLayoutWidget)
        self.MovieName.setText("")
        self.MovieName.setObjectName("MovieName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MovieName)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ShowRate = QtWidgets.QLabel(self.formLayoutWidget)
        self.ShowRate.setText("")
        self.ShowRate.setObjectName("ShowRate")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ShowRate)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.ShowPeople = QtWidgets.QLabel(self.formLayoutWidget)
        self.ShowPeople.setText("")
        self.ShowPeople.setObjectName("ShowPeople")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.ShowPeople)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(730, 620, 267, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.UseTips = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.UseTips.setObjectName("UseTips")
        self.horizontalLayout_3.addWidget(self.UseTips)
        self.UseTips.clicked.connect(self.msg)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1008, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "实时票房查询小程序"))
        self.DateLabel.setText(_translate("MainWindow", "日期："))
        self.TimeLabel.setText(_translate("MainWindow", "时间："))
        self.SumLabel.setText(_translate("MainWindow", "今日总票房："))
        self.Title.setText(_translate("MainWindow", "欢迎使用票房查询小程序~"))
        self.Sub_Rank.setText(_translate("MainWindow", "排名"))
        self.Sub_Name.setText(_translate("MainWindow", "影片名称"))
        self.Sub_ShowDays.setText(_translate("MainWindow", "上映天数"))
        self.Sub_CurSum.setText(_translate("MainWindow", "当日票房"))
        self.Sub_TotalBox.setText(_translate("MainWindow", "上映总票房"))
        self.combobox_Name.setText(_translate("MainWindow", "选择查看电影详细信息"))
        self.ChooseConfirmed.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "票房占比："))
        self.label_3.setText(_translate("MainWindow", "排片场次："))
        self.label_11.setText(_translate("MainWindow", "所选影片："))
        self.label_9.setText(_translate("MainWindow", "排片占比："))
        self.label_5.setText(_translate("MainWindow", "场均人次："))
        self.label_7.setText(_translate("MainWindow", "上座率："))
        self.label_2.setText(_translate("MainWindow", "——基于猫眼电影专业版"))
        self.UseTips.setText(_translate("MainWindow", "使用指南"))

    def msg(self):
        reply = QMessageBox.information(self, "使用提示", "通过下拉列表选择影片，点击确定即可查看详细信息",
                                        QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        print(reply)